language: node_js
node_js: stable
os:
    - linux
    - osx
install:
    - npm install
script:
    - npm run build
    - npm run nyc
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint; fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            npm run test:integ
        else
            # XXX: Spectron v11 seems broken on Linux
            # https://travis-ci.org/github/rhysd/tweet-app/jobs/719974471
            # xvfb-run npm run test:integ
            echo 'integ test skipped'
        fi
after_success:
    - npm install -g codecov
    - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
