language: node_js
node_js: stable
os:
    - linux
    - osx
install:
    - npm install
script:
    - npm run build
    - npm run coverage
# after_success:
#     - npm install -g codecov
#     - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
