name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build  # Building .js sources is necessary since eslint-plugin-node searches JavaScript sources
      - run: npm run lint
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: npm run nyc
      # TODO: Uncomment when upgrading spectron to v16 which supports Electron v14
      # - name: Run E2E tests (Linux)
      #   if: ${{ matrix.os == 'ubuntu-latest' }}
      #   run: |
      #     export DISPLAY=:99
      #     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      #     sleep 5 # Ensure to start Xvfb display server
      #     npm run test:integ
      # - name: Run E2E tests (not Linux)
      #   if: ${{ matrix.os != 'ubuntu-latest' }}
      #   run: npm run test:integ
      - name: Generate coverage report
        run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
