name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - run: npm ci
      - run: npm run build  # Building .js sources is necessary since eslint-plugin-node searches JavaScript sources
      - run: npm run lint
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run nyc
      - name: Generate coverage report
        run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
